version: "3.8"

services:
  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
